package levelSimple;

public class StringDifference {

	/**
	 * Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		String s="abcd";
		String t="abced";
		char ch=findStringDifference(s,t);
		System.out.println(ch);
	}
	private static char findStringDifference(String s,String t){
		char res = 0;
		int ss=0,tt=0;
		for(int i=0;i<s.length();i++){
			 ss+=(int)s.charAt(i);
		}
		for(int i=0;i<t.length();i++){
			 tt+=(int)t.charAt(i);
		}
		System.out.println(tt-ss);
		res=(char) (tt-ss);
		return res;
	}
}
